### ISSUE TITLE
Android gradle wrapper gradle-wrapper.properties does not exist.

### ISSUE THREAD

**Issue by javiervargas** [jollyjoker992/bc-ur-java#1]
Hi!

Could you please specify what the content of this file should be?

```
$ git clone https://github.com/jollyjoker992/bc-ur-java
Cloning into 'bc-ur-java'...
remote: Enumerating objects: 130, done.
remote: Counting objects: 100% (130/130), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 130 (delta 17), reused 127 (delta 14), pack-reused 0
Receiving objects: 100% (130/130), 2.47 MiB | 1.18 MiB/s, done.
Resolving deltas: 100% (17/17), done.
Checking connectivity... done.
javier@bitcoin:~$ cd bc-ur-java/
javier@bitcoin:~/bc-ur-java$ cd deps/
javier@bitcoin:~/bc-ur-java/deps$ ll
total 12
drwxrwxr-x 3 javier javier 4096 nov  2 21:04 ./
drwxrwxr-x 7 javier javier 4096 nov  2 21:04 ../
drwxrwxr-x 2 javier javier 4096 nov  2 21:04 bc-ur/
javier@bitcoin:~/bc-ur-java/deps$ cd bc-ur/
javier@bitcoin:~/bc-ur-java/deps/bc-ur$ ll
total 8
drwxrwxr-x 2 javier javier 4096 nov  2 21:04 ./
drwxrwxr-x 3 javier javier 4096 nov  2 21:04 ../
javier@bitcoin:~/bc-ur-java/deps/bc-ur$ cd ..
javier@bitcoin:~/bc-ur-java/deps$ git clone https://github.com/BlockchainCommons/bc-ur
Cloning into 'bc-ur'...
remote: Enumerating objects: 122, done.
remote: Counting objects: 100% (122/122), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 122 (delta 51), reused 98 (delta 30), pack-reused 0
Receiving objects: 100% (122/122), 125.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (51/51), done.
Checking connectivity... done.
javier@bitcoin:~/bc-ur-java/deps$ cd ..
javier@bitcoin:~/bc-ur-java$ cd android/
javier@bitcoin:~/bc-ur-java/android$ ll
total 44
drwxrwxr-x 5 javier javier 4096 nov  2 21:04 ./
drwxrwxr-x 7 javier javier 4096 nov  2 21:04 ../
drwxrwxr-x 3 javier javier 4096 nov  2 21:04 app/
-rw-rw-r-- 1 javier javier  950 nov  2 21:04 build.gradle
-rw-rw-r-- 1 javier javier  803 nov  2 21:04 CMakeLists.txt
drwxrwxr-x 3 javier javier 4096 nov  2 21:04 gradle/
-rwxrwxr-x 1 javier javier 5296 nov  2 21:04 gradlew*
-rw-rw-r-- 1 javier javier 2260 nov  2 21:04 gradlew.bat
drwxrwxr-x 2 javier javier 4096 nov  2 21:04 prebuilt/
-rw-rw-r-- 1 javier javier  120 nov  2 21:04 settings.gradle
javier@bitcoin:~/bc-ur-java/android$ ./gradlew clean connectedDebugAndroidTest
Exception in thread "main" java.lang.RuntimeException: Wrapper properties file '/home/javier/bc-ur-java/android/gradle/wrapper/gradle-wrapper.properties' does not exist.
	at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:43)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)
```

Thanks!

**Comment by jollyjoker992** [comment]
@javiervargas Thanks for testing it. I added missing files in [this commit](https://github.com/jollyjoker992/bc-ur-java/commit/b747cb8463041aa075c6d2d97944edd972aefda5). Please pull the code again and verify it.

**Comment by javiervargas** [comment]
I've checked library file succesfully.

```
*** ALL TESTS PASSED ***
make[1]: Leaving directory '/home/javier/bc-ur-java/deps/bc-ur/test'
~/bc-ur-java/java
Building libbc-ur.so
Checkout the release file at build/release/libbc-ur.so
```
Trying to create Jar file got error,  however all java classes are located on /bc-ur-java/java/build/classes/java/main/com/bc/ur.

```
./gradlew assembleRelease

FAILURE: Build failed with an exception.

* What went wrong:
Task 'assembleRelease' not found in root project 'BCUR-java'.
```

**Comment by jollyjoker992** [comment]
@javiervargas Sorry, just my mistake. Please use `./gradlew assemble` instead.

**Comment by ChristopherA** [comment]
@devrandom, do we have a "Tested ACK" from you?

**Comment by devrandom** [comment]
Just a concept ACK and an ACK on the overall (non BC UR specific) code.  I think it's best someone with more experience with the C++ library look at the details of the bindings to see if the API looks good and also see if there are any potential memory issues.

**Comment by ChristopherA** [comment]
@devrandom, understood.

Given that, @wolfmcnally are you able give an an ACK?

**Comment by wolfmcnally** [comment]
I looked over the API, and while it doesn't give access to the lower-level FountainEncoder/Decoder or Bytewords classes, that isn't a requirement for supporting UR translation. So LGTM!

**Comment by ChristopherA** [comment]
Ok. I have two ACKs. Merging!

**Comment by ChristopherA** [comment]
I mean ready for transfer :-)

**Comment by jollyjoker992** [comment]
Close since transferred to [BlockchainCommons repo](https://github.com/BlockchainCommons/bc-ur-java)
